### ISSUE TITLE
License added

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/PyloricNetwork#4]
@borismarin, @adrianq @adityagilra I'm adding license information to a number of OSB projects. Hope you are ok with your contributions to this repo being released under MIT license.

**Comment by adityagilra** [comment]
Yup, ok.
    On Wednesday, 5 December, 2018, 3:54:44 PM GMT+1, Padraig Gleeson <notifications@github.com> wrote:  
 
 
@borismarin, @adrianq @adityagilra I'm adding license information to a number of OSB projects. Hope you are ok with your contributions to this repo being released under MIT license.

**Comment by adrianq** [comment]
all good with me. thank you for asking!

**Comment by pgleeson** [comment]
Thanks folks!
